### ISSUE TITLE
1.7.10 Journal Not Readable

### ISSUE THREAD

**Issue by Faedelity** [mikaelsrozee/adventurers-amulets#2]
Guide-API apparently changed something after your last 1.7.10 version, and the Journal does not work any longer- the text on the first page is one immensely long line, and specific pages run off the bottom. They are no longer supporting 1.7.10, and I understand you might not be either, but I am willing to make an updated book using one of the systems that is still supported/working and release it as a mini-mod if you are okay with sending me the information that was in the original book. Or, if you are willing to release an update, I will happily send you a corrected book and you can replace the Guide-API version with little effort on your part.

**Comment by Faedelity** [comment]
Found the correct file, now I literally just need to know the character that would add line breaks, and I am willing to reformat this for you. Please? I would really rather not have to make a separate book in Mod X so people know how to use Adventurer's Amulets.

**Comment by msrcodes** [comment]
@NocturneBlock I'm not looking to support 1.7.10. I do however give full permission for you to add support into your mod to add compatability to this mod.
